name: stack_tower
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.18+18

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.18.0
  flame_audio: ^2.1.0
  shared_preferences: ^2.2.2
  google_mobile_ads: ^5.1.0
  games_services: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  assets:
    - assets/images/
    - assets/images/blocks/
    - assets/audio/backGroundMusic.mp3
    - assets/audio/bgm_1.mp3
    - assets/audio/bgm_2.mp3
    - assets/audio/blip.wav
    - assets/audio/game_over.mp3
    - assets/audio/perfect.mp3
    - assets/audio/place.mp3

  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
